### ISSUE TITLE
游戏/书本/电影/音乐

### ISSUE THREAD

**Issue by mfmpf** [Cubik65536/cubik-website#14]
你之前问过 游戏/书本/电影/音乐 这些页面怎么设置，我看你现在还没有设置好。你可以在这个仓库里看到教程：
https://github.com/mythsman/hexo-douban

另外，你博客的留言板好像用不了

**Comment by Cubik65536** [comment]
留言板需要登录才可以发送消息

书本那几个并非没设置完，我不打算用插件而且完全没往里写具体内容而已
